# Generated by Django 5.0.3 on 2024-03-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meatings',
            name='link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
