# Generated by Django 5.0.3 on 2024-04-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meatings',
            old_name='meating_name',
            new_name='meeting_name',
        ),
    ]
