# Generated by Django 5.0.3 on 2024-04-09 11:33

import meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_remove_meetings_meeting_name_meetings_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='duration',
            field=models.IntegerField(default=0, validators=[meetings.models.validate_positive_duration]),
        ),
    ]
