# Generated by Django 5.0.3 on 2024-03-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_tutor_verify',
            field=models.BooleanField(default=False),
        ),
    ]
