# Generated by Django 5.0.3 on 2024-04-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_is_tutor_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile/profile_image'),
        ),
    ]
