# Generated by Django 5.0.3 on 2024-04-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='customuser',
            name='person',
            field=models.CharField(choices=[('user', 'Regular User'), ('tutor', 'Tutor')], default='user', max_length=10),
        ),
    ]
