# Generated by Django 5.0.3 on 2024-04-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_customuser_is_tutor_customuser_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='person',
            field=models.CharField(choices=[('student', 'Student'), ('tutor', 'Tutor')], default='user', max_length=10),
        ),
    ]
