# Generated by Django 5.0.3 on 2024-03-23 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='module_content',
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.CharField(default='description', max_length=255),
        ),
        migrations.AddField(
            model_name='courses',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='courses',
            name='tutor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modules',
            name='module_content_ppt',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_content_video',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modules',
            name='module_type',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
