# Generated by Django 5.0.3 on 2024-03-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_modules_module_content_courses_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_content_ppt',
            field=models.FileField(blank=True, null=True, upload_to='modules/ppt'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='module_content_video',
            field=models.FileField(blank=True, null=True, upload_to='modules/video'),
        ),
    ]
