# Generated by Django 5.0.3 on 2024-04-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courses_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_content_video',
            field=models.FileField(default=0, upload_to='modules/video'),
            preserve_default=False,
        ),
    ]
