# Generated by Django 5.0.3 on 2024-04-01 10:57

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_modules_module_content_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(upload_to='courses/thumbnail', validators=[courses.models.validate_thumbnail_size]),
        ),
    ]
