# Generated by Django 5.0.3 on 2024-04-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_categories_courses_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modules',
            name='module_content_video',
            field=models.FileField(blank=True, null=True, upload_to='modules/video'),
        ),
    ]
