# Generated by Django 4.2.11 on 2024-05-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_modules_module_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='tutor',
        ),
    ]
