# Generated by Django 4.2.11 on 2024-05-13 11:55

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_files_thumbnail_alter_courses_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='thumbnail',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='files',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='courses/thumbnail', validators=[courses.models.validate_thumbnail_size]),
        ),
    ]
