# Generated by Django 4.2.11 on 2024-05-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_courses_thumbnail_alter_files_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.CharField(default='description', max_length=1000),
        ),
    ]
