# Generated by Django 5.0.3 on 2024-03-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_image', models.FileField(blank=True, null=True, upload_to='modules/carousel_image')),
            ],
        ),
    ]
