# Generated by Django 5.0.3 on 2024-03-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carouse',
            new_name='Carousel',
        ),
    ]
