# Generated by Django 5.0.3 on 2024-03-25 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notifications',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
