# Generated by Django 5.0.3 on 2024-04-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_remove_notifications_notifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.FileField(upload_to='modules/carousel_image'),
        ),
    ]
