# Generated by Django 5.0.3 on 2024-04-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_carousel_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.FileField(upload_to='carousel_image'),
        ),
    ]
