# Generated by Django 4.2.11 on 2024-05-20 17:20

import adminapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_alter_carousel_carousel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='carousel_image',
            field=models.FileField(upload_to='carousel_image', validators=[adminapp.models.validate_carousel_image_size]),
        ),
    ]
